spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:warm-tangent-413003-f49869804b3c.json
        project-id: warm-tangent-413003
        bucket: codi-bucket
    servlet:
      multipart:
        maxFileSize: 1000MB # 파일 하나의 최대 크기
        maxRequestSize: 3000MB  # 한 번에 최대 업로드 가능 용량

#JWT
jwt:
  secret: ${JWT_SECRET}
  refresh-token-validity-in-seconds: 1209600 # 14일
  access-token-validity-in-seconds: 43200 # 12시간

#OAuth2
security:
  oauth2:
    google:
      client-id: ${OAUTH2_CLIENT_ID}
      client-secret: ${OAUTH2_CLIENT_SECRET}
      redirect-uri: ${OAUTH2_REDIRECT_URI}
      token-uri: ${OAUTH2_TOKEN_URI}
      resource-uri: ${OAUTH2_RESOURCE_URI}

#KAKAO KEY
kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

---
# default environment
spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local, dev, prod, test